[package]
name = "my_ecs"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = "1.7.0"

[dev-dependencies]
criterion = { version = "0.5.0", features = ["async"] }

[[bench]]
name = "my_ecs_bench"
harness = false
